version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::248583331331:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-Z5PSOMR4RS4Z"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::248583331331:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-AGKVFOQ6HPFK"
cloudformation_execution_role = "arn:aws:iam::248583331331:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-LAQETIBNCYHA"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-gidbyjhxeq5n"
image_repository = ""
region = "us-west-1"

[test]
[test.pipeline_bootstrap]
[test.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::248583331331:role/aws-sam-cli-managed-test-pip-PipelineExecutionRole-1HHVWBUOYXGNN"
cloudformation_execution_role = "arn:aws:iam::248583331331:role/aws-sam-cli-managed-test-CloudFormationExecutionR-1C6TE0JNFXU3C"
artifacts_bucket = "aws-sam-cli-managed-test-pipeline-artifactsbucket-43ob47kbaopk"
image_repository = ""
region = "us-west-2"
